baseURL = 'https://example.org/'
disableKinds = ['rss','sitemap','taxonomy','term']

printPathWarnings = true

defaultContentLanguage = 'en'

[languages.en]
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1
title = 'Hugo GitHub Issue #13346 (en)'

[languages.de]
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
weight = 2
title = 'Hugo GitHub Issue #13346 (de)'
